### ISSUE TITLE
url is not working anymore

### ISSUE THREAD

**Issue by biturbo** [Jarthianur/sensorics#2]
Just wanted to install the sensorics, I have a BMP280, should work with the BME280 code
but the Download `git clone https://github.com/groeck/i2c-tools.git` is not working anymore

**Comment by Jarthianur** [comment]
Ok I have to fix that.
The repo isn't available anymore. Maybe I'll switch to the official system i2c-tools.

**Comment by Jarthianur** [comment]
Switched to official libi2c-dev.
